// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  form: dynamic(() => import("./Form")),
  menu_item: dynamic(() => import("./MenuItem")),
};
